---
# tasks file for deploy_app

#- name: download_url
#  debug: "msg={{ download_url }}"
#- name: liferay_archive
#  debug: "msg={{ liferay_archive }}"
#- name: liferay_home
#  debug: "msg={{ liferay_home }}"

- name: Download Liferay distributive
  get_url:
    url: "{{ download_url }}"
    dest: "{{ liferay_archive }}"
    validate_certs: false

- name: Extract App archive to App dir
  ansible.builtin.unarchive:
    src: "{{ liferay_archive }}"
    dest: "{{ liferay_home | dirname }}"
    remote_src: yes

- name: Find Liferay Tomcat sh files
  find:
    paths: "{{ liferay_home }}/{{ tomcat_version }}/bin"
    patterns: '*.sh'
  register: liferay_tomcat_sh_files

- name: Changing perm of Liferay Tomcat sh files adding "+x"
  file:
    dest: "{{ item.path }}"
    mode: "a+x"
  with_items: "{{ liferay_tomcat_sh_files.files }}"

- name: Upload portal-ext.properties to the App dir
  copy:
    src: "{{ liferay_config_file }}"
    dest: "{{ liferay_home }}"
    mode: 600
...