---
- name: "Create and configure ansible user"
  hosts: cserver2
  #become: True

  tasks:
    - name: "Create Ansible Group"
      group:
        name: "{{ ansible_group_name }}"
        state: present

    - name: "Create Ansible User"
      user:
        name: "{{ ansible_user_name }}"
        group: "{{ ansible_group_name }}"
        shell: /bin/bash
        password: "{{ ansible_user_pass }}"

    - name: "Grant Ansible User sudo permissions"
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^{{ ansible_user_name }}    ALL="
        line: "{{ ansible_user_name }}    ALL=(ALL)    NOPASSWD:  ALL"
        validate: /usr/sbin/visudo -cf %s

    - name: "Generate RSA keypair"
      delegate_to: localhost
      run_once: True
      openssh_keypair:
        path: "{{ keypair_path }}"
        type: rsa
        size: 2048

    - name: "Set authorized key for Ansible user"
      authorized_key:
        user: "{{ ansible_user_name }}"
        state: present
        key: "{{ lookup('file', keypair_path + '.pub') }}"

  vars:
    ansible_group_name: ansible
    ansible_user_name: ansible
    ansible_user_pass: "afq24t!GFwq3Gt2yt$yh4H3%^U35tEHG59t6uwy3Qt12"
    keypair_path: /home/ansible/ansible.key
...
