---
- name: Deploy Liferay (PostgreSQL based)
  hosts: STAGING
  become: True
  gather_facts: False

#  roles:
#    - { role: deploy_java, when: ansible_os_family == 'Debian' }
#    - { role: deploy_app, when: ansible_os_family == 'Debian' }
#    - { role: deploy_db, when: ansible_os_family == 'Debian' }

  tasks:
    - name: Start Liferay
      command: "sh /var/lib/liferay-ce-portal-7.4.3.112-ga112/tomcat-9.0.83/bin/startup.sh"
      when: ansible_os_family == 'Debian'
...