- name: Create DB {{ db_name }}
  postgresql_db:
    name: "{{ db_name }}"

- name: Upload SQL to remote
  copy:
    src: roles/deploy_db/files/create-postgresql.sql
    dest: "{{ sql_destination }}"
    mode: 600
#      become: yes
#      become_user: postgres

- name: Run SQL
  community.postgresql.postgresql_script:
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    db: "{{ db_name }}"
    path: "{{ sql_destination }}{{ sql_filename }}"