- block: # For RedHat
    - name: "Install packages on RedHat"
      dnf: "name={{ item }} state=present"
      with_items:
        - postgresql
        - postgresql-server
        - python3-pip

    - name: "Install Python packages on RedHat"
      pip: "name={{ item }}  state=present"
      with_items:
        - psycopg2-binary
  when: ansible_os_family == "RedHat"

- block: # For Debian
    - name: "Install packages on Debian"
      apt: "name={{ item }} state=present"
      with_items:
        - postgresql
        - postgresql-server
        - python3-pip

    - name: "Install Python packages on Debian"
      pip: "name={{ item }}  state=present"
      with_items:
        - psycopg2-binary
  when: ansible_os_family == "Debian"
