# test db
- name: "Load SQL script into a variable"
  set_fact:
    test_sql: "{{ lookup('file', 'roles/deploy_db/files/migration.sql') }}"

- name: "Execute script from variable"
  command: "psql {{ db_name }} -c '{{ test_sql }}'"
  become_user: postgres
  register: sql_response_variable

- debug: var={{ item }}
  loop:
    - postgres_data
    - test_sql
    - sql_response_variable.stdout
